name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Set up environment variables
        run: |
          echo "PORT=8080" >> ${{ env.GITHUB_ENV }}
          echo "MYSQL_DB=flashbite" >> ${{ env.GITHUB_ENV }}
          echo "MYSQL_PORT=3306" >> ${{ env.GITHUB_ENV }}
          echo "MYSQL_ROOT_PASSWORD=integrador03202401*" >> ${{ env.GITHUB_ENV }}
          echo "MYSQL_USERNAME=flashbite" >> ${{ env.GITHUB_ENV }}
          echo "MYSQL_HOST=flashbite-mysql-server.mysql.database.azure.com" >> ${{ env.GITHUB_ENV }}
          echo "MAILER_SERVICE=gmail" >> ${{ env.GITHUB_ENV }}
          echo "MAILER_EMAIL=jorgepinilla2002@gmail.com" >> ${{ env.GITHUB_ENV }}
          echo "MAILER_SECRET_KEY=paff vtbb kkvp wmmj" >> ${{ env.GITHUB_ENV }}
          echo "JWT_SEED=flashbiteIntegrador" >> ${{ env.GITHUB_ENV }}
          echo "AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=flashbiteimgs;AccountKey=iNrqu/Br6j/noNYZnwuNm5Lj3DasRO7XL7L5lfq/MfeqkkpeiqJCwRnd3LI02un6oyMklpJ5hY3E+AStRZJfHw==;EndpointSuffix=core.windows.net" >> ${{ env.GITHUB_ENV }}
      - name: Delete Dependencies
        run: npm ci
      - name: Install Dependencies
        run: npm install

      - name: npm run build
        run: npm run build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: nodejsflashbite
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
